 repos:
  # Typescript
  - repo: local
    hooks:
      - id: eslint
        stages: [commit]
        name: eslint
        entry: bash -c "yarn lint"
        language: node
      - id: prettier
        stages: [commit]
        name: prettier
        entry: bash -c "yarn format:fix"
        language: node
